services:
  postgres-task-management-system:
    image: postgres:latest
    container_name: postgres-task-management-system
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_management_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_task_management_system:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  task-management-system-app:
    restart: always
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres-task-management-system
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres-task-management-system:5432/task_management_system_db'
      JAVA_OPTS: '-Xmx512m'

volumes:
  pg_task_management_system:
